import test from 'node:test';import assert from 'node:assert/strict';import {database} from '../scripts/adapter.mjs';import {adminData} from '../src/admin.mjs';import {JSDOM} from 'jsdom';import {renderAdminBilling} from '../public/admin-billing.js';
test('owner billing view isolates permissions, filters cached records and never calls Stripe',async t=>{
 const DB=database(),env={DB,APP_ENV:'staging'},old=globalThis.fetch;globalThis.fetch=()=>{throw Error('must not fetch Stripe');};t.after(()=>{DB.close();globalThis.fetch=old;});
 for(const role of ['owner','admin','support','member']){await DB.prepare('INSERT INTO users VALUES(?,?,?,?)').bind(role,role+'@test.example','private-hash','brand').run();if(role!=='member')await DB.prepare('INSERT INTO admin_roles VALUES(?,?)').bind(role,role).run();}
 for(const role of ['admin','support','member'])await assert.rejects(adminData(env,{id:role},new URL('https://mart.test/?view=billing')),e=>e.status===403);
 for(let i=0;i<27;i++){const id='u'+i;await DB.prepare('INSERT INTO users VALUES(?,?,?,?)').bind(id,id+'@test.example','private-hash','brand').run();await DB.prepare('INSERT INTO billing_accounts(user_id,customer_id,status,plan_id,cancel_at_period_end,updated_at,lock_token) VALUES(?,?,?,?,?,?,?)').bind(id,'cus_'+id,i===0?'past_due':'active','brand',i===1?1:0,i,'private-lock').run();}
 const get=params=>adminData(env,{id:'owner'},new URL('https://mart.test/?view=billing'+params));let d=await get('');assert.equal(d.total,27);assert.equal(d.rows.length,25);assert.equal(d.stats.attention,1);assert.equal(d.stats.ending,1);assert.doesNotMatch(JSON.stringify(d),/private-hash|private-lock|lock_token|session_params/);
 assert.equal((await get('&page=2')).rows.length,2);assert.equal((await get('&billing_filter=attention')).rows[0].id,'u0');assert.equal((await get('&billing_filter=ending')).rows[0].id,'u1');assert.equal((await get('&q=%25')).total,0);await assert.rejects(get('&billing_filter=bad'),e=>e.status===400);
 await DB.prepare("INSERT INTO billing_downgrades(id,user_id,subscription_id,from_plan,to_plan,period,from_price,target_price,effective_at,status,created_at,updated_at) VALUES('d','u2','sub_2','brand','growth','monthly','price_b','price_g',1800000000,'review',1,1)").run();d=await get('&billing_filter=attention');assert.equal(d.total,2);assert.equal(d.rows.find(r=>r.id==='u2').downgrade_status,'review');
 assert.equal((await DB.prepare("SELECT plan_id FROM users WHERE id='u0'").first()).plan_id,'brand');
});
test('billing cards escape data and explain cached status and pending changes',()=>{
 const root=new JSDOM('<section></section>').window.document.querySelector('section');renderAdminBilling({root,data:{stats:{accounts:1,attention:1,ending:0},rows:[{email:'<img src=x>',plan_id:'brand',status:'active',updated_at:0,upgrade_status:'review',upgrade_plan:'growth',upgrade_amount:30000,customer_id:'<script>bad</script>'}]}});
 assert.equal(root.querySelector('img'),null);assert.equal(root.querySelector('script'),null);assert.match(root.textContent,/ไม่ใช่สถานะสด/);assert.match(root.textContent,/ต้องให้ผู้ดูแลตรวจสอบ/);assert.match(root.textContent,/อย่าให้ร้านค้าชำระซ้ำ/);
});
