import test from 'node:test';import assert from 'node:assert/strict';import {database} from '../scripts/adapter.mjs';import {hash,passwordHash} from '../src/security.mjs';import worker from '../src/worker.mjs';import {effectivePlan} from '../src/plans.mjs';
test('Owner manages invites, expiring plans, status and filters without changing billing or granting roles',async()=>{
 const DB=database(),mail=[],env={DB,APP_ENV:'production',SIGNUP_ENABLED:'true',MAIL_FROM:'mart@test.example',POSTMARK_SERVER_TOKEN:'fixture',RECOVERY_ORIGIN:'https://mart.test',CHECKOUT_HOSTS:'thaimart.com',MEDIA:{get:async()=>({body:'image'})},MAIL_FETCH:async(u,o)=>{mail.push(JSON.parse(o.body));return Response.json({ErrorCode:0});}};
 const call=(path,actor='owner',body,origin='https://mart.test')=>worker.fetch(new Request('https://mart.test'+path,{method:body?'POST':'GET',headers:{Cookie:'mart_session='+actor,Origin:origin},...(body?{body:JSON.stringify(body)}:{})}),env,{waitUntil(){}});
 const manage=b=>call('/api/admin/members','owner',{reason:'Customer promotion support',...b});
 try{
 for(const id of ['owner','staff','seller']){await DB.prepare('INSERT INTO users VALUES(?,?,?,?)').bind(id,id+'@test.example',await passwordHash('password-for-test-2026'),'free').run();await DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await hash(id),id,Math.floor(Date.now()/1000)+3600).run();}await DB.prepare("INSERT INTO admin_roles VALUES('owner','owner'),('staff','admin')").run();
 assert.equal((await call('/api/admin/members','staff',{action:'create',email:'new@test.example',reason:'test reason'})).status,403);assert.equal((await call('/api/admin/members','owner',{action:'create'},'https://evil.test')).status,403);
 const create=await manage({action:'create',email:'new@test.example'});assert.equal(create.status,200);const id=(await create.json()).id;assert.equal((await manage({action:'create',email:'new@test.example'})).status,409);
 assert.equal((await manage({action:'plan',user_id:id,plan:'growth',expires:null})).status,200);
 env.APP_ENV='staging';await call('/api/register/request','',{email:'new@test.example'});assert.equal(mail.length,1);const token=mail[0].TextBody.match(/#token=([a-f0-9]+)/)[1];
 const completion={token,password:'new-password-2026',confirm_password:'new-password-2026'};const completed=await Promise.all([call('/api/register/complete','',completion),call('/api/register/complete','',completion)]);assert.deepEqual(completed.map(r=>r.status).sort(),[200,400]);assert.equal((await effectivePlan(env,{id,plan_id:'free'})).id,'growth');assert.equal((await DB.prepare('SELECT plan_id FROM users WHERE id=?').bind(id).first()).plan_id,'free');assert.equal((await DB.prepare('SELECT status FROM member_controls WHERE user_id=?').bind(id).first()).status,'active');
 env.APP_ENV='production';const expires=Math.floor(Date.now()/1000)+3600;await manage({action:'plan',user_id:'seller',plan:'brand',expires});assert.equal((await effectivePlan(env,{id:'seller',plan_id:'free'})).id,'brand');await DB.prepare("UPDATE member_controls SET override_expires=1 WHERE user_id='seller'").run();assert.equal((await effectivePlan(env,{id:'seller',plan_id:'free'})).id,'free');await manage({action:'plan',user_id:'seller',plan:null,expires:null});
 await DB.prepare("INSERT INTO shops(id,owner_id,name,slug,published) VALUES('s','seller','Seller','seller',1)").run();await DB.prepare("INSERT INTO products(id,shop_id,name,source_url,status,image_key) VALUES('p','s','Product','https://thaimart.com/products/abc','published','seller/img')").run();await DB.prepare("INSERT INTO media VALUES('seller/img','seller','image/png',5)").run();
 assert.equal((await call('/shop/seller')).status,200);
 assert.equal((await manage({action:'status',user_id:'owner',status:'banned',confirm_email:'owner@test.example'})).status,403);
 assert.equal((await manage({action:'status',user_id:'seller',status:'banned',confirm_email:'wrong'})).status,400);
 for(const status of ['suspended','banned','deleted']){assert.equal((await manage({action:'status',user_id:'seller',status,confirm_email:'seller@test.example'})).status,200);assert.equal((await call('/shop/seller')).status,404);assert.equal((await call('/go/p')).status,404);assert.ok([403,404].includes((await call('/media/seller%2Fimg')).status));assert.equal((await call('/api/login','',{email:'seller@test.example',password:'password-for-test-2026'})).status,403);assert.equal((await DB.prepare("SELECT COUNT(*) n FROM sessions WHERE user_id='seller'").first()).n,0);}
 const removed=await(await call('/api/admin?view=users&status=deleted')).json();assert.equal(removed.total,1);assert.equal(removed.rows[0].id,'seller');assert.equal((await(await call('/api/admin?view=users&role=owner')).json()).total,1);assert.equal((await(await call('/api/admin?view=users&plan=free')).json()).total,4);
 await manage({action:'status',user_id:'seller',status:'active',confirm_email:'seller@test.example'});assert.equal((await call('/shop/seller')).status,200);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM products').first()).n,1);assert.ok((await DB.prepare("SELECT COUNT(*) n FROM admin_audit WHERE action='member_status'").first()).n>=4);
 }finally{DB.close();}
});
