import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';

test('plan comparison uses API prices and preserves usage while switching periods',async()=>{
 const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
 const start=source.indexOf('async function plans(){');
 const end=source.indexOf('\nfunction recovery()',start+1);
 const code=source.slice(start,end);
 const dom=new JSDOM('<div id="content"></div>');
 const root=dom.window.document.querySelector('#content');
 const items=[{id:'free',name:'Free',monthly:0,yearly:0},{id:'starter',name:'Starter',monthly:19900,yearly:199000},{id:'growth',name:'Growth',monthly:49900,yearly:499000},{id:'brand',name:'Brand',monthly:99000,yearly:990000}].map(p=>({...p,shops:1,products:30,branding:false}));
 let requests=0,mounts=0;
 const run=new Function('$','api','state','esc','money','paidThemes','mountAccountUsage','toast','mountBilling','send',code+';return plans();');
 await run(s=>dom.window.document.querySelector(s),async()=>{requests++;return items;},{tab:'plans',plan:{id:'brand',staging_test:true}},s=>s,c=>'฿'+(c/100).toLocaleString('th-TH',{maximumFractionDigits:2}),()=>true,({root})=>{mounts++;root.textContent='usage';},e=>{throw Error(e);},()=>{},()=>{});
 const usage=root.querySelector('#account-usage');
 const buttons=root.querySelectorAll('[data-plan-period]');
 buttons[1].focus();buttons[1].click();
 const prices=[...root.querySelectorAll('[data-plan-price]')];
 assert.match(prices[1].textContent,/฿1,990/);
 assert.match(prices[1].textContent,/฿165.83/);
 assert.match(prices[1].textContent,/฿398/);
 assert.match(prices[2].textContent,/฿4,990/);
 assert.match(prices[3].textContent,/฿9,900/);
 assert.equal(prices[0].querySelector('.plan-saving'),null);
 assert.equal(buttons[1].getAttribute('aria-pressed'),'true');
 assert.equal(dom.window.document.activeElement,buttons[1]);
 buttons[0].click();
 assert.match(prices[1].textContent,/฿199/);
 assert.equal(prices[1].querySelector('.plan-saving'),null);
 assert.equal(buttons[1].getAttribute('aria-pressed'),'false');
 assert.equal(root.querySelector('#account-usage'),usage);
 assert.equal(requests,1);assert.equal(mounts,1);
});
