ALTER TABLE shops ADD COLUMN logo_key TEXT NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN cover_key TEXT NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN seo_title TEXT NOT NULL DEFAULT '';
ALTER TABLE shops ADD COLUMN seo_description TEXT NOT NULL DEFAULT '';
