import {escape as e} from './security.mjs';
import {productRecord,priceLabel,priceRange,imageURL,plainHTML} from './content.mjs';
export function storefront(shop,rows,origin,staging=true){
 const products=rows.map(productRecord),canonical=origin+'/shop/'+encodeURIComponent(shop.slug);
 const cards=products.map(p=>{const gallery=p.gallery.length?p.gallery:(p.image_key?[{key:p.image_key,alt:p.name}]:[]);return `<article class="product-card" id="product-${e(p.id)}"><div class="product-gallery">${gallery.map((im,i)=>`<a href="${imageURL(im.key)}" target="_blank" rel="noopener"><img src="${imageURL(im.key)}" alt="${e(im.alt||p.name)}" loading="lazy" ${i?'':'fetchpriority="low"'}></a>`).join('')||'<div class="no-photo">ยังไม่มีรูปสินค้า</div>'}</div><div class="product-info">${p.category?`<span class="product-category">${e(p.category)}</span>`:''}<h2>${e(p.name)}</h2><strong>${priceLabel(p)}</strong>${p.variants.length?`<details class="variant-details"><summary>ตัวเลือกสินค้าและราคา · ${p.variants.length} แบบ</summary><div class="table-wrap"><table><thead><tr><th>ตัวเลือก / SKU</th><th>ราคา</th><th>ข้อมูลเพิ่มเติม</th></tr></thead><tbody>${p.variants.map(v=>`<tr><td>${v.image_key?`<img class="variant-thumb" src="${imageURL(v.image_key)}" alt="${e(v.attributes.map(a=>a.value).join(' / '))}" loading="lazy">`:''}${e(v.attributes.map(a=>a.key+': '+a.value).join(' · '))}<small>${e(v.sku)}</small></td><td>${v.price==null?'ดูที่ Thaimart':'฿'+(v.price/100).toLocaleString('th-TH')}</td><td>${e([v.weight&&'น้ำหนัก: '+v.weight,v.dimensions&&'ขนาด: '+v.dimensions,v.available===false&&'ต้นทางระบุว่าไม่พร้อมขาย ณ วันที่นำเข้า'].filter(Boolean).join(' · '))}</td></tr>`).join('')}</tbody></table></div><small>หน่วยตามข้อมูลร้านค้า ตรวจราคาและสต็อกล่าสุดที่ Thaimart</small></details>`:''}<a class="button" href="/go/${e(p.id)}" rel="nofollow">เลือกแบบและซื้อที่ Thaimart ↗</a><details class="product-details"><summary>รายละเอียดสินค้า</summary><div class="rich-content">${p.description_html||plainHTML(p.description)}</div></details></div></article>`;}).join('');
 const schema={'@context':'https://schema.org','@type':'CollectionPage',name:shop.name,description:shop.description,url:canonical,mainEntity:{'@type':'ItemList',itemListElement:products.map((p,i)=>{const range=priceRange(p);return {'@type':'ListItem',position:i+1,item:{'@type':'Product',name:p.name,description:p.description,url:canonical+'#product-'+p.id,image:(p.gallery.length?p.gallery:p.image_key?[{key:p.image_key}]:[]).map(im=>origin+imageURL(im.key)),...(p.category?{category:p.category}:{}),...(range?{offers:p.variants.length?{'@type':'AggregateOffer',priceCurrency:'THB',lowPrice:range[0]/100,highPrice:range[1]/100,offerCount:p.variants.length,url:canonical+'#product-'+p.id}:{'@type':'Offer',priceCurrency:'THB',price:range[0]/100,url:canonical+'#product-'+p.id}}:{})}};})}};
 const json=JSON.stringify(schema).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(shop.name)} | Lync to Mart</title><meta name="description" content="${e((shop.description||'เลือกชมสินค้าจาก '+shop.name).slice(0,180))}"><meta name="robots" content="${staging?'noindex,nofollow':'index,follow'}"><link rel="canonical" href="${e(canonical)}"><meta property="og:title" content="${e(shop.name)}"><meta property="og:description" content="${e(shop.description.slice(0,180))}"><meta property="og:url" content="${e(canonical)}"><link rel="stylesheet" href="/styles.css?v=video1"><script type="application/ld+json">${json}</script></head><body class="store-body"><header class="store-top"><a href="${e(canonical)}">${e(shop.name)}</a><span>ร้านค้าออนไลน์</span></header><main class="store-main"><section class="store-intro"><span class="eyebrow">ยินดีต้อนรับสู่ร้านของเรา</span><h1>${e(shop.name)}</h1><p>${e(shop.description)}</p>${shop.line_url?`<a class="button light" href="${e(shop.line_url)}" rel="noopener noreferrer">ติดต่อร้านทาง LINE</a>`:''}</section><div class="section-heading"><h2>สินค้าของเรา</h2><span>${products.length} รายการ</span></div><section class="catalog">${cards||'<p class="empty">ร้านกำลังเตรียมสินค้า กลับมาเยี่ยมชมอีกครั้งนะคะ</p>'}</section><p class="store-note">เลือกตัวเลือกสินค้าและชำระเงินที่ Thaimart · ราคาและสต็อกอาจเปลี่ยนแปลง ตรวจสอบที่ต้นทางก่อนซื้อ</p></main>${shop.branding?'<footer class="store-footer">Powered by <strong>Lync to Mart</strong></footer>':''}</body></html>`;
}
